import Head from "next/head";
import { Container } from "@mui/material";
import TodoForm from "../components/TodoForm";
import TodoList from "../components/TodoList";

export default function Home() {
  return (
    <Container maxWidth="md">
      <Head>
        <title>Hodo Next Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TodoForm />

      <TodoList />
    </Container>
  );
}
